FLASK_APP=backend/server.py
FLASK_ENV=production

SECRET_KEY=vdphLT-5aWHUmf3lnDTBlE-cj0lvZcN0-XSEOVqdGL0IWh9_cUbONMAy6zfbSFyIpN78atIPvbNP0EPT5sWDwg
JWT_SECRET_KEY=sGaqnc8sgLjMT6SQeXO6T7PBlnqRv7c6SD4jy4JvGxXMmDv6Sv_YIBfrOgv1n9RBqC6CmcbOFuNo_ybZt9UTRw
DATABASE_URL=sqlite:///backend/instance/bank.db
